[[constraint]]
  branch = "master"
  name = "github.com/jasonwinn/geocoder"

[[constraint]]
  name = "github.com/shawntoffel/darksky"
  version = "1.2.1"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.2.2"

[prune]
  go-tests = true
  unused-packages = true
